version: '3.9'
services:
  db:
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ssword1
      - POSTGRES_DATABASE=invoicerappdb
    ports:
      - '5432:5432'
    volumes: 
      - pgdata:/var/lib/postgresql/data
volumes:
  db:
    driver: local